### PR TITLE
refactoring + code formatting + test data

### PR DESCRIPTION
**Pull request by hurdad**

### CODE REVIEW

**Comment by antonmks** [comment]
There are conflicts in 2 files : 
CONFLICT (content): Merge conflict in src/Makefile
Auto-merging moderngpu
Adding as moderngpu~c9c8ce6f31d383c1b27a6cccb6778baba8bc1797 instead

Not sure what to do about them - could you fix it somehow ?

**Comment by hurdad** [comment]
So I tried to sync with your latest updates but I am getting errors..

First issue has to do with the Makefile update you did recently regarding the bison.xx , that needs to be completely overwritten, as i changed name of the name to alenka.xx ...

The other issues has to do with moving the 'moderngpu' submodule to the root directory. 

If you give me write access, I might be able to fix the conflicts..

-alex

**Comment by antonmks** [comment]
Ok, I added you. See if that works ...

**Comment by hurdad** [comment]
ok, I will give this a try after lunch. thanks

**Pull request closed without merging**
